DESTINATIONS = ["Alicante", "Amsterdam", "Bali", "Bangkok", 
                "Barcelona", "Belfast", "Benidorm", "Berlin", "Budapest",
                "Dalaman", "Dubai", "Dublin", "Edinburgh", "Faro",
                "Florida", "Hong Kong", "Ibiza",
                "Lanzarotte", "Las Vegas", "Lisbon",
                "Los Angeles", "Malaga", "Malta",
                "Murcia", "New York", "Orlando", "Paris",
                "Prague", "Rome", "Tenerife", "Toronto"]

AIRPORT_CODES = {
    "Alicante": "ALC",
    "Amsterdam": "AMS",
    "Bali": "DPS",
    "Bangkok": "BKK",
    "Barcelona": "BCN",
    "Belfast": "BHD",
    "Benidorm": "ALC",
    "Berlin": "BER",
    "Budapest": "BUD",
    "Dalaman": "DLM",
    "Dubai": "DXB",
    "Dublin": "DUB",
    "Edinburgh": "EDI",
    "Faro": "FAO",
    "Florida": "ORL",
    "Hong Kong": "HKG",
    "Ibiza": "IBZ",
    "Lanzarotte": "ACE",
    "Las Vegas": "LAS",
    "Lisbon": "LIS",
    "Los Angeles": "LAX",
    "Malaga": "AGP",
    "Malta": "MLA",
    "Murcia": "RMU",
    "New York": "NYC",
    "Orlando": "ORL",
    "Paris": "PAR",
    "Prague": "PRG",
    "Rome": "ROM",
    "Tenerife": "TCI",
    "Toronto": "YTO"
                 }